= 安装jMonkeyEngine
:author: yan
:revnumber:
:revdate: 2018-01-22 15:45:10
:relfileprefix: ../
:imagesdir: ..
:experimental:
ifdef::env-github,env-browser[:outfilesuffix: .adoc]


== 下载和安装

*在安装之前，请查阅<<bsd_license#,jME3开源许可证>>、<<engine/features#,jME3功能说明>>和<<engine/requirements#,开发需求>>，* 然后选择其中一个选项：
[cols="4", options="header"]
|===

a|
<a| 推荐
<a| 可选
<a| 可选

a| 目标
a| 进行jMonkeyEngine可视化开发
a| 在其他IDE中集成 jMonkeyEngine3
a| 利用源码来编译自定义引擎

a| 下载地址
a| link:https://github.com/jMonkeyEngine/sdk/releases/tag/stable[jMonkeyEngine SDK]
a| link:https://github.com/jMonkeyEngine/jmonkeyengine/releases[jMonkeyEngine]
a| link:https://github.com/jMonkeyEngine/jmonkeyengine[源代码]

a| 内容
a| * 源代码 +
* 已编译的jar包 +
* javadoc +
* SDK
a| * 源代码 +
* 最新版本的jar包 +
* javadoc
a| * 源代码

|===

=== jMonkeyEngine SDK

jMonkeyEngine SDK(简称 SDK 或 jME SDK) 是 jME3 团队为提高开发者的工作效率，基于
NetBeans 开发的**可视化集成开发工具**。它为开发者提供了模型预览、场景编辑、地形编辑、材
质编辑等3D游戏开发所需的常用功能。

jME SDK 创建的是基于Ant的项目，任何Java IDE都可以导入。我们建议其他IDE的用户也下载
jME SDK，并选择 menu:File[Import Project > External Project Assets] 来创建一个不包
含任何代码的资源项目，用以管理项目中的资源文件(如模型、材质、贴图等)。这样您就可以在自己选
择的IDE中编码，并利用jME SDK来将您的模型转换成 .j3o 格式。

* <<sdk/index#,学习使用SDK>>
* <<sdk/create_project#,使用SDK创建工程>>

=== jMonkeyEngine

jME3 的本体是一个 3D 游戏引擎框架，表现为一组名为 `jme3-{模块名}-{版本号}.jar` 的类库。
任何Java IDE都可以通过集成 jME3 的类库来获得 3D 支持。更棒的是，jME3 采用模块化开发方
法，将引擎的功能分解到各个 jar 文件中，开发者可以根据自己的需要来选择依赖哪些类库。

TIP: 例如，对于只需要 3D 可视化项目来说，就不需要 `jme3-networking.jar` 中的联网功能。

下面的文章将介绍如何在不同环境中集成JME3：

* <<getting-start/with_maven#,Maven或Gradle>>
* <<getting-start/with_netbeans#,NetBeans>>
* <<getting-start/with_eclipse#, Eclipse>>
* <<getting-start/with_android_studio#,Android Studio>>
* <<getting-start/with_intellij_idea#,Intellij IDEA>>

=== 源代码

jME3 是一款免费开源的3D游戏引擎，使用纯Java开发而成，项目托管于 link:https://github.com/jMonkeyEngine/jmonkeyengine[github.com]。jME3 采用 link:https://gradle.org/[Gradle] 项目结构，编译源代码需要先安装 JDK 和 Gradle。

下面的文章将介绍如何获取和编译 jME3 的源代码。

* <<install/build_from_sources#,编译JME3源码>>
* <<install/build_jme3_sources_with_netbeans#,在NetBeans中编译JME3源码>>
* <<install/simpleapplication_from_the_commandline#,在(Linux)命令行下开发JME3>>
