= Wiki目录结构计划
:author: jmecn
:revnumber:
:revdate: 2018-01-17 16:30:18
:relfileprefix:
:imagesdir:
:experimental:
ifdef::env-github,env-browser[:outfilesuffix: .adoc]

I'm planning to reorganize wiki contents, like this:

== Getting-Start

This part will help user to download, install, run the Engine and SDK.

== Beginner's tutorials

This part will go througth the first 13 HelloXX tutorials.

== SDK

This part will tell user how to use jMonkeyEngine SDK. Such as:

* creating projects
* import and view 3d models
* use terrain editor
* ..
* logging and debug
* applcation deployment

== Engine

This part should introduce the features of the Engine to user.

== Asset-Pipeline

This part is especially for game artist, should telling about how to make
jMonkeyEngine compatible game assets.

== Programming

This part is especially for game programmer, should dive deep into jME3 and
tell how to tinker with the engine.

Most contents of this part came from former "advanced" folder.

== Shader

This part is especially for technique artist, should telling about how create
jMonkeyEngine compatible materials and shaders.

Maybe I should combine this part into "5. Asset-Pipeline".

== Platforms

This part should tell about the experience and pitfalls when developing on
different platforms.

* Windows
* Linux
* MacOS
* Android
* iOS
* Steam
* VR
* HTML5 (?)

== Builds

This part is for recording history of different jME3 builds. Maybe one day we
can really have a Roadmap here.

Of couse we can just go and read git commit history, but I still prefer a simple
feature list for each build.

== Contribution

This part tells how to contribute to jME3:

* Wiki
* Engine
* SDK

Also it should tell user how to find the already exist contributes on Github.com。

== Planning

Example structures:

[source]
----

bsd_license.adoc
team.adoc
getting-start/
getting-start/download/
getting-start/download/source.adoc
getting-start/download/engine.adoc
getting-start/download/sdk.adoc
getting-start/install/
getting-start/install/sdk.adoc
getting-start/install/with-android-studio.adoc
getting-start/install/with-commandline.adoc
getting-start/install/with-eclipse.adoc
getting-start/install/with-gradle.adoc
getting-start/install/with-intellij-idea.adoc
getting-start/install/with-maven.adoc
getting-start/install/with-netbeans.adoc
getting-start/run-demos.adoc
getting-start/requirements.adoc
getting-start/terminology.adoc
getting-start/faq.adoc
beginner/
beginner/hello_simpleapplication.adoc
beginner/hello_node.adoc
beginner/hello_asset.adoc
beginner/hello_loop.adoc
beginner/hello_input.adoc
beginner/hello_material.adoc
beginner/hello_animation.adoc
beginner/hello_picking.adoc
beginner/hello_collision.adoc
beginner/hello_terrain.adoc
beginner/hello_audio.adoc
beginner/hello_effects.adoc
beginner/hello_physics.adoc
sdk/
sdk/create-project.adoc
sdk/code-editor.adoc
sdk/import-3d-model.adoc
sdk/scene-composer.adoc
sdk/play-audio.adoc
sdk/..
sdk/deployment/
sdk/deployment/pc.adoc
sdk/deployment/android.adoc
sdk/deployment/ios.adoc
engine/
engine/animation/
engine/animation/overview.adoc
engine/animation/animation.adoc
engine/animation/motion-path.adoc
engine/animation/cinematics.adoc
engine/animation/skeleton.adoc
engine/animation/..
engine/asset/
engine/asset/overview.adoc
engine/asset/assetmanager.adoc
engine/asset/assetpackage.adoc
engine/asset/asset-pipeline.adoc
engine/gui/
engine/gui/nifty-gui/..
engine/gui/lemur/..
engine/media/audio.adoc
engine/media/video.adoc
engine/media/..
engine/performance/
engine/performance/statusview.adoc
engine/performance/profile.adoc
engine/performance/..
engine/physics/
engine/physics/bulletappstate.adoc
engine/physics/..
engine/rendering/
engine/rendering/overview.adoc
engine/rendering/lighting-and-shadow/..
engine/rendering/materials/..
engine/rendering/particlesystem/..
engine/rendering/post-process-effects/..
engine/rendering/shader/..
engine/rendering/texture/..
engine/scene/
engine/scene/scenegraph.adoc
engine/scene/spatial.adoc
engine/scene/node.adoc
engine/scene/geometry.adoc
engine/scene/..
engine/terrain/
engine/terrain/terrain.adoc
engine/terrain/terrain-collision.adoc
engine/terrain/terrain-lighting.adoc
engine/networking/..
asset-pipeline/overview.adoc
asset-pipeline/file-format.adoc
asset-pipeline/photoshop/..
asset-pipeline/blender/..
asset-pipeline/3dsmax/..
asset-pipeline/maya/..
programming/
programming/asset/
programming/asset/assetlocator.adoc
programming/asset/assetloader.adoc
programming/asset/customlocator.adoc
programming/asset/customloader.adoc
programming/asset/assetconfig.adoc
programming/asset/assetcache.adoc
programming/asset/asseteventlistener.adoc
programming/camera/
programming/camera/flybycamera.adoc
programming/camera/chasecam.adoc
programming/camera/..
programming/data-structure/
programming/data-structure/mesh.adoc
programming/data-structure/animation.adoc
programming/data-structure/..
programming/game-logic/
programming/game-logic/main-loop.adoc
programming/game-logic/appstate.adoc
programming/game-logic/control.adoc
programming/game-logic/customcontrol.adoc
programming/game-logic/updategeometrylogic.adoc
programming/game-logic/..
programming/graphcis/
programming/graphcis/rendering-pipeline.adoc
programming/graphcis/renderstate.adoc
programming/graphcis/renderbucket.adoc
programming/graphcis/viewports.adoc
programming/graphics/..
programming/input/
programming/input/actionlistener.adoc
programming/input/analoglistener.adoc
programming/input/rawinputlistener.adoc
programming/input/touchlistener.adoc
programming/input/device/mouse.adoc
programming/input/device/keyborad.adoc
programming/input/device/touch-screen.adoc
programming/input/device/joystick.adoc
programming/input/device/..
programming/math/
programming/math/..
programming/logging/..
programming/networking/..
programming/scripting/..
shader/
shader/material-define.adoc
shader/globals.adoc
shader/uniforms.adoc
shader/attributes.adoc
shader/glsllib.adoc
shader/shader-node.adoc
shader/..
platforms/
platforms/desktop/..
platforms/mobile/..
platforms/vistual reality/..
builds/
builds/jme3.0.adoc
builds/jme3.1.adoc
builds/jme3.2.adoc
builds/..
contribution/
contribution/how-to.adoc
contribution/wiki/..
contribution/engine/..
contribution/sdk/..
----
