= jMonkeyEngine 3 教程 (1) - SimpleApplication
:author: (翻译 jmecn)
:revnumber:
:revdate: 2018/01/22 15:49
:keywords: beginner, intro, documentation, init, simpleapplication, basegame
:relfileprefix: ../
:imagesdir: ..
:experimental:
ifdef::env-github,env-browser[:outfilesuffix: .adoc]


上一篇: <<getting-start/index#,下载和安装>>,
下一篇: <<beginner/hello_node#,节点>>

*先决条件:* 这个教程假设你已经 <<sdk/index#,安装jMonkeyEngine SDK>>.

在这个教程系列，我们假设你使用jMonkeyEngine <<sdk#,SDK>>。作为中高级Java开发者，你会很快发现你可以在任何ide(NetBeans IDE, Eclipse, IntelliJ) 甚至 <<jme3/simpleapplication_from_the_commandline#,命令行模式>>中开发jMonkeyEngine代码。

那么开始我们的第一个jMonkeyEngine3应用程序。

== 创建一个工程项目

在jMonkeyEngine SDK:

. 在主菜单选择 `menu:File[New Project]`。 
. 选择样例 `menu:JME3[Basic Game]`。
. 点击 btn:[Next]。
.. 输入项目名，比如 "`HelloWorldTutorial`"。
.. 输入新项目的路径，比如 `jMonkeyProjects`。
. 点击 btn:[Finish]

这会创建一个基本jme3应用。点击运行：你会看到一个蓝色立方体。详情了解 <<sdk/project_creation#,创建jME3工程>> 

[TIP]
====
我们建议你自己跟着跟着教程。或者，你可以在jMonkeyEngine SDK创建一个 <<sdk/sample_code#,JmeTests>> 项目模板。它会创建一个带有 `jme3test.helloworld` （和更多）的样例。比如，你可以使用JmeTests来检查你的代码。
====


== 继承(Extend) SimpleApplication

在这个教程，你的工程项目需要包含jme3test.helloworld包和HelloJME.java文件。

在jMonkeyEngine SDK:

. 在 `Source Packages` ， btn:[鼠标右键点击] "`mygame`" 包。
.. 选择： `menu:Refactor[Rename]`
.. 输入新名称： `jme3test.helloworld` 
.. 完成后点击 btn:[Refactor]。
. 在重构后的包， btn:[鼠标右键点击] `Main.java` 类。
.. 选择：`menu:Refactor[Rename]`
.. 输入新名称： `HelloJME3`
.. 完成后点击 btn:[Refactor]。

对余下的教程同样使用这个基本流程

TIP：余下的教程都使用一样的 `jme3test.helloworld` 包。只需重构 `Main.java` 类名到教程样例的类名，而不是对每个教程都创建新项目。

== 代码样例

用以下代码，替换HelloJME3.java原来的代码。

[source,java]
----

package jme3test.helloworld;

import com.jme3.app.SimpleApplication;
import com.jme3.material.Material;
import com.jme3.scene.Geometry;
import com.jme3.scene.shape.Box;
import com.jme3.math.ColorRGBA;

/** Sample 1 - how to get started with the most simple JME 3 application.
 * Display a blue 3D cube and view from all sides by
 * moving the mouse and pressing the WASD keys. */
public class HelloJME3 extends SimpleApplication {

    public static void main(String[] args){
        HelloJME3 app = new HelloJME3();
        app.start(); // start the game
    }

    @Override
    public void simpleInitApp() {
        Box b = new Box(1, 1, 1); // create cube shape
        Geometry geom = new Geometry("Box", b);  // create cube geometry from the shape
        Material mat = new Material(assetManager,
          "Common/MatDefs/Misc/Unshaded.j3md");  // create a simple material
        mat.setColor("Color", ColorRGBA.Blue);   // set color of material to blue
        geom.setMaterial(mat);                   // set the cube's material
        rootNode.attachChild(geom);              // make the cube appear in the scene
    }
}
----

btn:[鼠标右键点击] `HelloJME3` 类，然后选择 `Run`。 如果jME3的设置对话框弹出，确认默认设置。

. 你应该看到一个窗口显示一个3d立方体。
. 按下 kbd:[W] kbd:[A] kbd:[S] kbd:[D] 键和移动鼠标来航行。
. 在坐下角可以查看FPS（刷新率）和object count（物体数量）信息。 你将会在开发过程中运用到这些信息，你也会在发行版本中移除它。（确认第14行显示有14个物体和914个顶点。）
. 按下 kbd:[Esc] 关闭程序。

恭喜你~然后一起来看看它是如何运作的！

== 理解代码

以上代码初始化了场景和启动程序。

=== 启动SimpleApplication

Look at the first line. Your HelloJME3.java class extends `com.jme3.app.SimpleApplication`.

看第1行，你的 HelloJME3.java 类继承了`com.jme3.app.SimpleApplication`。

[source,java]
----

public class HelloJME3 extends SimpleApplication {
  // your code...
}

----

每个JME3游戏是一个 `com.jme3.app.SimpleApplication` 类的实例。SimpleApplication是一个最简单的应用：它管理3d场景，检测用户输入，更新游戏状况和自动渲染窗口。这些是游戏引擎的核心作用。你通过继承这个类，然后修改定制你自己的游戏。

你通过main()函数来启动所有JME3游戏，就像所有标准Java程序一样。

. 实例化你基于 `SimpleApplication`的类
. 调用程序的 `start()` 函数来启动游戏引擎。

[source,java]
----

    public static void main(String[] args){
        HelloJME3 app = new HelloJME3(); // instantiate the game 实例化游戏
        app.start();                     // start the game! 启动游戏
    }

----

`app.start();` 行打开应用窗口。让我们一起学习如何向窗口（场景）加入一些东西。

=== 理解术语
[cols="2", options="header"]
|===

a|你想要做什么
a|你如何用JME3术语来描述它

a|你想创建一个立方体
a|我创建一个 1x1x1 Box shape（盒状）的Geometry（几何形状）

a|你想用蓝颜色
a|我创建一个蓝颜色的材质

a|你想给立方体上蓝色
a|我设置几何形状的材质

a|你想把立方体放进场景
a|我attach（附着）几何形状到rootNode（根节点）

a|你想立方体放在窗口中央
a|我在 `Vector3f.ZERO` 创建几何形状

|===
如果你对这些单词不熟悉，查看 <<jme3/the_scene_graph#,the Scene Graph>> 

=== 初始化场景

查看剩下的代码。`simpleInitApp()`函数是在程序开始自动调用一次。所有JME3游戏一定含有这个函数。在函数 `simpleInitApp()` 中，你在游戏开始前加载游戏对象。

[source,java]
----

    public void simpleInitApp() {
       // your initialization code... 你的初始化代码。。。
    }

----

立方体的初始化代码如下：

[source,java]
----

    public void simpleInitApp() {
        Box b = new Box(1, 1, 1); // create a 1x1x1 box shape
        Geometry geom = new Geometry("Box", b);  // create a cube geometry from the box shape
        Material mat = new Material(assetManager,
          "Common/MatDefs/Misc/Unshaded.j3md");  // create a simple material
        mat.setColor("Color", ColorRGBA.Blue);   // set color of material to blue
        geom.setMaterial(mat);                   // set the cube geometry 's material
        rootNode.attachChild(geom);              // make the cube geometry appear in the scene
    }

----

一个JME3游戏有以下初始化过程：

. 初始化游戏对象：
** 你创建或加载对象和放置它们。
** 你通过附着对象到 `rootNode` 来让他们在场景中显示。
** *Examples* 加载玩家，地形，天空，敌对目标，障碍物，...，和放置它们到它们的起始位置。

. 初始化变量：
** 你创建变量来跟踪游戏状况。
** 你设置变量的初始值。
** *Examples:* 设置 `score` 到0，设置 `health` 到100%， ...

. 初始化按键和鼠标的监听：
** 以下输入已经提前设置：
*** kbd:[W] kbd:[A] kbd:[S] kbd:[D] 按键 - 移动
*** 鼠标移动和方向键 - 转动摄像机
*** kbd:[Esc]  按键 - 退出游戏

** 定义你自己的附加按键和鼠标监听。
** *比如：*点击鼠标来发射子弹，按下 kbd:[Space] 来跳跃， ...


=== The Future of SimpleApplication


There are plans to change SimpleApplication. Sometime back it was decided that we should really re-factor the Application class. SimpleApplication especially is a mess of "`magic`" protected fields that on the one hand makes it really easy to slam some simple one-class application together, but on the other hand does new users no favors because they have no idea where 'cam' and 'assetManager' come from. Unfortunately, lots of code refers to Application and it's tough to change... especially the app states.

So, we hatched a plan to convert the Application class to an interface. This would give us some freedom to iterate on a new set of application base classes. You can read about the changes link:https://hub.jmonkeyengine.org/t/jmonkeyengine-3-1-alpha-4-released/35478[here]. As said before we are envisioning a better design that is not enforced today, but that is already usable.

If you look at SimpleApplication default constructor you will understand how it works.

[source,java]
----
public SimpleApplication() {   
    this(new StatsAppState(), new FlyCamAppState(), new AudioListenerState(), new DebugKeysAppState());}
----

Basically the application is injected upon construction with the default AppStates. Let's look at the second constructor.

[source,java]
----
public SimpleApplication( AppState... initialStates ) {   
    super(initialStates);
}
----

It allows you to specify what AppState you want for your application. So SimpleApplication is handy for test projects (I very often use it as is) but I recommend for a full blown-game to use it like this:

[source,java]
----
public class MyGame extends SimpleApplication {

    public MyGame(){
         super(new MyCustomSate(), new AnotherState(), ....);
    }

    public static void main(String[] args) {
        MyGame app = new MyGame();
        app.start();
    }

}
----

Then have all logic implemented in <<jme3/advanced/application_states#,AppStates>> and your SimpleApplication will never change much, except when you want to add a bootstrap AppState (or maybe you can have an AppState that manages AppStates...), SimpleApplication is just the list of states you are using.

In future versions, all the code in SimpleApplication will be refactored in AppStates (InputHandlingState, RenderAppState, whatever) and you will decide what you want to use. However, for legacy sake we kept the code as is for now.


== Conclusion

You have learned that a SimpleApplication is a good starting point because it provides you with:

*  A `simpleInitApp()` method where you create objects.
*  A `rootNode` where you attach objects to make them appear in the scene.
*  Useful default input settings that you can use for navigation in the scene.

When developing a game application, you want to:

.  Initialize the game scene
.  Trigger game actions
.  Respond to user input.

The now following tutorials teach how you accomplish these tasks with the jMonkeyEngine 3.

Continue with the <<beginner/hello_node#,Hello Node>> tutorial, where you learn more details about how to initialize the game world, also known as the scene graph.

'''

See also:

*  <<getting-start/index#,安装jME3>>
*  <<jme3/simpleapplication_from_the_commandline#,SimpleApplication From the Commandline>>
*  <<sdk/project_creation#,创建jME3工程>>
*  <<jme3/advanced/application_states#,AppStates>>
