= jMonkeyEngine 3 教程 (1) - SimpleApplication
:author: (翻译 jmecn)
:revnumber:
:revdate: 2018/01/22 15:49
:keywords: beginner, intro, documentation, init, simpleapplication, basegame
:relfileprefix: ../
:imagesdir: ..
:experimental:
ifdef::env-github,env-browser[:outfilesuffix: .adoc]


上一篇: <<getting-start/index#,下载和安装>>,
下一篇: <<beginner/hello_node#,节点>>

*先决条件:* 这个教程假设你已经 <<sdk/index#,安装jMonkeyEngine SDK>>.

在这个教程系列，我们假设你使用jMonkeyEngine <<sdk#,SDK>>。作为中高级Java开发者，你会很快发现你可以在任何ide(NetBeans IDE, Eclipse, IntelliJ) 甚至 <<jme3/simpleapplication_from_the_commandline#,命令行模式>>中开发jMonkeyEngine代码。

那么开始我们的第一个jMonkeyEngine3应用程序。

== 创建一个工程项目

在jMonkeyEngine SKL:

. 在主菜单选择 `menu:File[New Project]`。 
. 选择样例 `menu:JME3[Basic Game]`。
. 点击 btn:[Next]。
.. 输入项目名，比如 "`HelloWorldTutorial`"。
.. 输入新项目的路径，比如 `jMonkeyProjects`。
. 点击 btn:[Finish]

这会创建一个基本jme3应用。点击运行：你会看到一个蓝色立方体。详情了解 <<sdk/project_creation#,创建jME3工程>> 

[TIP]
====
我们建议你自己跟着跟着教程。或者，你可以在jMonkeyEngine SDK创建一个 <<sdk/sample_code#,JmeTests>> 项目模板。它会创建一个带有 `jme3test.helloworld` （和更多）的样例。比如，你可以使用JmeTests来检查你的代码。
====


== 继承Extend SimpleApplication

在这个教程，你的工程项目需要包含jme3test.helloworld包和HelloJME.java文件。

In the jMonkeyEngine SDK:

.  In the `Source Packages` node of your project, btn:[RMB] select the "`mygame`" package.
..  Choose: `menu:Refactor[Rename]`
..  Enter the New Name: `jme3test.helloworld`
..  Click btn:[Refactor] when ready.
.  In the newly refactored package, btn:[RMB] select the `Main.java` class.
..   Choose: `menu:Refactor[Rename]`
..  Enter the New Name: `HelloJME3`
..  Click btn:[Refactor] when ready.

You follow this same basic procedure for the remaining tutorials.

TIP: The remaining tutorials all use the same `jme3test.helloworld` package. Just refactor the "`Main.java`" class name to the tutorial examples class name rather than creating a new project for each.

== Code Sample

Replace the contents of the HelloJME3.java file with the following code.

[source,java]
----

package jme3test.helloworld;

import com.jme3.app.SimpleApplication;
import com.jme3.material.Material;
import com.jme3.scene.Geometry;
import com.jme3.scene.shape.Box;
import com.jme3.math.ColorRGBA;

/** Sample 1 - how to get started with the most simple JME 3 application.
 * Display a blue 3D cube and view from all sides by
 * moving the mouse and pressing the WASD keys. */
public class HelloJME3 extends SimpleApplication {

    public static void main(String[] args){
        HelloJME3 app = new HelloJME3();
        app.start(); // start the game
    }

    @Override
    public void simpleInitApp() {
        Box b = new Box(1, 1, 1); // create cube shape
        Geometry geom = new Geometry("Box", b);  // create cube geometry from the shape
        Material mat = new Material(assetManager,
          "Common/MatDefs/Misc/Unshaded.j3md");  // create a simple material
        mat.setColor("Color", ColorRGBA.Blue);   // set color of material to blue
        geom.setMaterial(mat);                   // set the cube's material
        rootNode.attachChild(geom);              // make the cube appear in the scene
    }
}
----

btn:[RMB] select the `HelloJME3` class and choose `Run`. If a jME3 settings dialog pops up, confirm the default settings.

.  You should see a simple window displaying a 3D cube.
.  Press the kbd:[W] kbd:[A] kbd:[S] kbd:[D] keys and move the mouse to navigate around.
.  Look at the FPS text and object count information in the bottom left. You will use this information during development, and you will remove it for the release. (To read the numbers correctly, consider that the 14 lines of text counts as 14 objects with 914 vertices.)
.  Press kbd:[Esc]  to close the application.

Congratulations! Now let's find out how it works!


== Understanding the Code

The code above has initialized the scene, and started the application.


=== Start the SimpleApplication

Look at the first line. Your HelloJME3.java class extends `com.jme3.app.SimpleApplication`.

[source,java]
----

public class HelloJME3 extends SimpleApplication {
  // your code...
}

----

Every JME3 game is an instance of the `com.jme3.app.SimpleApplication` class. The SimpleApplication class is the simplest example of an application: It manages a 3D scene graph, checks for user input, updates the game state, and automatically draws the scene to the screen. These are the core features of a game engine. You extend this simple application and customize it to create your game.

You start every JME3 game from the main() method, as every standard Java application:

.  Instantiate your `SimpleApplication`-based class
.  Call the application's `start()` method to start the game engine.

[source,java]
----

    public static void main(String[] args){
        HelloJME3 app = new HelloJME3(); // instantiate the game
        app.start();                     // start the game!
    }

----

The `app.start();` line opens the application window. Let's learn how you put something into this window (the scene) next.


=== Understanding the Terminology
[cols="2", options="header"]
|===

a|What you want to do
a|How you say that in JME3 terminology

a|You want to create a cube.
a|I create a Geometry with a 1x1x1 Box shape.

a|You want to use a blue color.
a|I create a Material with a blue Color property.

a|You want to colorize the cube blue.
a|I set the Material of the Box Geometry.

a|You want to add the cube to the scene.
a|I attach the Box Geometry to the rootNode.

a|You want the cube to appear in the center.
a|I create the Box at the origin = at `Vector3f.ZERO`.

|===

If you are unfamiliar with the vocabulary, read more about <<jme3/the_scene_graph#,the Scene Graph>> here.


=== Initialize the Scene

Look at rest of the code sample. The `simpleInitApp()` method is automatically called once at the beginning when the application starts. Every JME3 game must have this method. In the `simpleInitApp()` method, you load game objects before the game starts.

[source,java]
----

    public void simpleInitApp() {
       // your initialization code...
    }

----

The initialization code of a blue cube looks as follows:

[source,java]
----

    public void simpleInitApp() {
        Box b = new Box(1, 1, 1); // create a 1x1x1 box shape
        Geometry geom = new Geometry("Box", b);  // create a cube geometry from the box shape
        Material mat = new Material(assetManager,
          "Common/MatDefs/Misc/Unshaded.j3md");  // create a simple material
        mat.setColor("Color", ColorRGBA.Blue);   // set color of material to blue
        geom.setMaterial(mat);                   // set the cube geometry 's material
        rootNode.attachChild(geom);              // make the cube geometry appear in the scene
    }

----

A typical JME3 game has the following initialization process:

.  You initialize game objects:
**  You create or load objects and position them.
**  You make objects appear in the scene by attaching them to the `rootNode`.
**  *Examples:* Load player, terrain, sky, enemies, obstacles, …, and place them in their start positions.

.  You initialize variables:
**  You create variables to track the game state.
**  You set variables to their start values.
**  *Examples:* Set the `score` to 0, set `health` to 100%, …

.  You initialize keys and mouse actions:
**  The following input bindings are pre-configured:
***  kbd:[W] kbd:[A] kbd:[S] kbd:[D] keys – Move around in the scene
***  Mouse movement and arrow keys – Turn the camera
***  kbd:[Esc]  key – Quit the game

**  Define your own additional keys and mouse click actions.
**  *Examples:* Click to shoot, press kbd:[Space] to jump, …



=== The Future of SimpleApplication


There are plans to change SimpleApplication. Sometime back it was decided that we should really re-factor the Application class. SimpleApplication especially is a mess of "`magic`" protected fields that on the one hand makes it really easy to slam some simple one-class application together, but on the other hand does new users no favors because they have no idea where 'cam' and 'assetManager' come from. Unfortunately, lots of code refers to Application and it's tough to change... especially the app states.

So, we hatched a plan to convert the Application class to an interface. This would give us some freedom to iterate on a new set of application base classes. You can read about the changes link:https://hub.jmonkeyengine.org/t/jmonkeyengine-3-1-alpha-4-released/35478[here]. As said before we are envisioning a better design that is not enforced today, but that is already usable.

If you look at SimpleApplication default constructor you will understand how it works.

[source,java]
----
public SimpleApplication() {   
    this(new StatsAppState(), new FlyCamAppState(), new AudioListenerState(), new DebugKeysAppState());}
----

Basically the application is injected upon construction with the default AppStates. Let's look at the second constructor.

[source,java]
----
public SimpleApplication( AppState... initialStates ) {   
    super(initialStates);
}
----

It allows you to specify what AppState you want for your application. So SimpleApplication is handy for test projects (I very often use it as is) but I recommend for a full blown-game to use it like this:

[source,java]
----
public class MyGame extends SimpleApplication {

    public MyGame(){
         super(new MyCustomSate(), new AnotherState(), ....);
    }

    public static void main(String[] args) {
        MyGame app = new MyGame();
        app.start();
    }

}
----

Then have all logic implemented in <<jme3/advanced/application_states#,AppStates>> and your SimpleApplication will never change much, except when you want to add a bootstrap AppState (or maybe you can have an AppState that manages AppStates...), SimpleApplication is just the list of states you are using.

In future versions, all the code in SimpleApplication will be refactored in AppStates (InputHandlingState, RenderAppState, whatever) and you will decide what you want to use. However, for legacy sake we kept the code as is for now.


== Conclusion

You have learned that a SimpleApplication is a good starting point because it provides you with:

*  A `simpleInitApp()` method where you create objects.
*  A `rootNode` where you attach objects to make them appear in the scene.
*  Useful default input settings that you can use for navigation in the scene.

When developing a game application, you want to:

.  Initialize the game scene
.  Trigger game actions
.  Respond to user input.

The now following tutorials teach how you accomplish these tasks with the jMonkeyEngine 3.

Continue with the <<beginner/hello_node#,Hello Node>> tutorial, where you learn more details about how to initialize the game world, also known as the scene graph.

'''

See also:

*  <<getting-start/index#,安装jME3>>
*  <<jme3/simpleapplication_from_the_commandline#,SimpleApplication From the Commandline>>
*  <<sdk/project_creation#,创建jME3工程>>
*  <<jme3/advanced/application_states#,AppStates>>
